export interface EmojiData {
  char: string;
  name: string;
  category: string;
  keywords: string[];
}

export const emojiData: EmojiData[] = [
  // Smileys & People
  { char: '😀', name: 'grinning face', category: 'smileys', keywords: ['smile', 'happy', 'joy'] },
  { char: '😃', name: 'grinning face with big eyes', category: 'smileys', keywords: ['smile', 'happy', 'joy'] },
  { char: '😄', name: 'grinning face with smiling eyes', category: 'smileys', keywords: ['smile', 'happy', 'joy'] },
  { char: '😁', name: 'beaming face with smiling eyes', category: 'smileys', keywords: ['smile', 'happy', 'joy'] },
  { char: '😆', name: 'grinning squinting face', category: 'smileys', keywords: ['smile', 'happy', 'joy'] },
  { char: '😅', name: 'grinning face with sweat', category: 'smileys', keywords: ['smile', 'happy', 'joy', 'sweat'] },
  { char: '🤣', name: 'rolling on the floor laughing', category: 'smileys', keywords: ['laugh', 'lol', 'rofl'] },
  { char: '😂', name: 'face with tears of joy', category: 'smileys', keywords: ['laugh', 'lol', 'tears', 'joy'] },
  { char: '🙂', name: 'slightly smiling face', category: 'smileys', keywords: ['smile', 'happy'] },
  { char: '🙃', name: 'upside-down face', category: 'smileys', keywords: ['silly', 'upside down'] },
  { char: '😉', name: 'winking face', category: 'smileys', keywords: ['wink', 'flirt'] },
  { char: '😊', name: 'smiling face with smiling eyes', category: 'smileys', keywords: ['smile', 'happy', 'blush'] },
  { char: '😇', name: 'smiling face with halo', category: 'smileys', keywords: ['angel', 'halo', 'innocent'] },
  { char: '🥰', name: 'smiling face with hearts', category: 'smileys', keywords: ['love', 'hearts', 'affection'] },
  { char: '😍', name: 'smiling face with heart-eyes', category: 'smileys', keywords: ['love', 'hearts', 'crush'] },
  { char: '🤩', name: 'star-struck', category: 'smileys', keywords: ['star', 'eyes', 'wow'] },
  { char: '😘', name: 'face blowing a kiss', category: 'smileys', keywords: ['kiss', 'love', 'flirt'] },
  { char: '😗', name: 'kissing face', category: 'smileys', keywords: ['kiss', 'love'] },
  { char: '😚', name: 'kissing face with closed eyes', category: 'smileys', keywords: ['kiss', 'love'] },
  { char: '😙', name: 'kissing face with smiling eyes', category: 'smileys', keywords: ['kiss', 'love'] },
  { char: '😋', name: 'face savoring food', category: 'smileys', keywords: ['yum', 'delicious', 'food'] },
  { char: '😛', name: 'face with tongue', category: 'smileys', keywords: ['tongue', 'silly'] },
  { char: '😜', name: 'winking face with tongue', category: 'smileys', keywords: ['wink', 'tongue', 'silly'] },
  { char: '🤪', name: 'zany face', category: 'smileys', keywords: ['crazy', 'silly', 'zany'] },
  { char: '😝', name: 'squinting face with tongue', category: 'smileys', keywords: ['tongue', 'silly'] },
  { char: '🤑', name: 'money-mouth face', category: 'smileys', keywords: ['money', 'rich', 'dollar'] },
  { char: '🤗', name: 'hugging face', category: 'smileys', keywords: ['hug', 'open', 'hands'] },
  { char: '🤭', name: 'face with hand over mouth', category: 'smileys', keywords: ['oops', 'shock', 'giggle'] },
  { char: '🤫', name: 'shushing face', category: 'smileys', keywords: ['quiet', 'shush', 'shh'] },
  { char: '🤔', name: 'thinking face', category: 'smileys', keywords: ['think', 'hmmm', 'ponder'] },
  { char: '🤐', name: 'zipper-mouth face', category: 'smileys', keywords: ['secret', 'quiet', 'mouth'] },
  { char: '🤨', name: 'face with raised eyebrow', category: 'smileys', keywords: ['curious', 'skeptical'] },
  { char: '😐', name: 'neutral face', category: 'smileys', keywords: ['neutral', 'poker face'] },
  { char: '😑', name: 'expressionless face', category: 'smileys', keywords: ['expressionless', 'bored'] },
  { char: '😶', name: 'face without mouth', category: 'smileys', keywords: ['quiet', 'silent'] },
  { char: '😏', name: 'smirking face', category: 'smileys', keywords: ['smirk', 'sly', 'flirt'] },
  { char: '😒', name: 'unamused face', category: 'smileys', keywords: ['unamused', 'bored', 'unhappy'] },
  { char: '🙄', name: 'face with rolling eyes', category: 'smileys', keywords: ['eye roll', 'sarcasm'] },
  { char: '😬', name: 'grimacing face', category: 'smileys', keywords: ['grimace', 'awkward'] },
  { char: '🤥', name: 'lying face', category: 'smileys', keywords: ['lie', 'pinocchio'] },
  { char: '😌', name: 'relieved face', category: 'smileys', keywords: ['relieved', 'peaceful'] },
  { char: '😔', name: 'pensive face', category: 'smileys', keywords: ['sad', 'pensive'] },
  { char: '😪', name: 'sleepy face', category: 'smileys', keywords: ['sleepy', 'zzz'] },
  { char: '🤤', name: 'drool', category: 'smileys', keywords: ['drool', 'delicious'] },
  { char: '😴', name: 'sleeping face', category: 'smileys', keywords: ['sleep', 'zzz'] },
  { char: '😷', name: 'face with medical mask', category: 'smileys', keywords: ['sick', 'mask', 'doctor'] },
  { char: '🤒', name: 'face with thermometer', category: 'smileys', keywords: ['sick', 'ill', 'fever'] },
  { char: '🤕', name: 'face with head-bandage', category: 'smileys', keywords: ['sick', 'hurt', 'injury'] },
  { char: '🤢', name: 'nauseated face', category: 'smileys', keywords: ['sick', 'gross', 'nausea'] },
  { char: '🤮', name: 'face vomiting', category: 'smileys', keywords: ['sick', 'gross', 'puke'] },
  { char: '🤧', name: 'sneezing face', category: 'smileys', keywords: ['sick', 'sneeze', 'cold'] },
  { char: '🥵', name: 'hot face', category: 'smileys', keywords: ['hot', 'heat', 'fever'] },
  { char: '🥶', name: 'cold face', category: 'smileys', keywords: ['cold', 'freeze', 'winter'] },
  { char: '😵', name: 'dizzy face', category: 'smileys', keywords: ['dizzy', 'shock'] },
  { char: '🤯', name: 'exploding head', category: 'smileys', keywords: ['mind blown', 'shock', 'wow'] },
  { char: '🤠', name: 'cowboy hat face', category: 'smileys', keywords: ['cowboy', 'hat', 'silly'] },
  { char: '🥳', name: 'partying face', category: 'smileys', keywords: ['party', 'celebrate', 'birthday'] },
  { char: '😎', name: 'smiling face with sunglasses', category: 'smileys', keywords: ['cool', 'sunglasses', 'swag'] },
  { char: '🤓', name: 'nerd face', category: 'smileys', keywords: ['nerd', 'geek', 'glasses'] },
  { char: '🧐', name: 'face with monocle', category: 'smileys', keywords: ['monocle', 'fancy'] },
  { char: '😕', name: 'confused face', category: 'smileys', keywords: ['confused', 'puzzled'] },
  { char: '😟', name: 'worried face', category: 'smileys', keywords: ['worried', 'sad'] },
  { char: '🙁', name: 'slightly frowning face', category: 'smileys', keywords: ['frown', 'sad'] },
  { char: '☹️', name: 'frowning face', category: 'smileys', keywords: ['frown', 'sad'] },
  { char: '😮', name: 'face with open mouth', category: 'smileys', keywords: ['wow', 'shock', 'surprise'] },
  { char: '😯', name: 'hushed face', category: 'smileys', keywords: ['hush', 'silent', 'wow'] },
  { char: '😲', name: 'astonished face', category: 'smileys', keywords: ['wow', 'surprise', 'shock'] },
  { char: '😳', name: 'flushed face', category: 'smileys', keywords: ['flushed', 'blush', 'embarrassed'] },
  { char: '🥺', name: 'pleading face', category: 'smileys', keywords: ['plead', 'puppy eyes', 'sad'] },
  { char: '😦', name: 'frowning face with open mouth', category: 'smileys', keywords: ['wow', 'surprise'] },
  { char: '😧', name: 'anguished face', category: 'smileys', keywords: ['anguish', 'shock', 'sad'] },
  { char: '😨', name: 'fearful face', category: 'smileys', keywords: ['fear', 'scared', 'shock'] },
  { char: '😰', name: 'face with open mouth and cold sweat', category: 'smileys', keywords: ['scared', 'sweat', 'shock'] },
  { char: '😥', name: 'sad but relieved face', category: 'smileys', keywords: ['sad', 'relieved', 'sweat'] },
  { char: '😢', name: 'crying face', category: 'smileys', keywords: ['cry', 'sad', 'tears'] },
  { char: '😭', name: 'loudly crying face', category: 'smileys', keywords: ['cry', 'sad', 'tears', 'sob'] },
  { char: '😱', name: 'face screaming in fear', category: 'smileys', keywords: ['scream', 'fear', 'scared'] },
  { char: '😖', name: 'confounded face', category: 'smileys', keywords: ['confuse', 'frustrated'] },
  { char: '😣', name: 'persevering face', category: 'smileys', keywords: ['struggle', 'frustrated'] },
  { char: '😞', name: 'disappointed face', category: 'smileys', keywords: ['sad', 'disappointed'] },
  { char: '😓', name: 'downcast face with sweat', category: 'smileys', keywords: ['sad', 'sweat', 'stress'] },
  { char: '😩', name: 'weary face', category: 'smileys', keywords: ['weary', 'tired', 'sad'] },
  { char: '😫', name: 'tired face', category: 'smileys', keywords: ['tired', 'exhausted', 'weary'] },
  { char: '🥱', name: 'yawning face', category: 'smileys', keywords: ['yawn', 'tired', 'sleepy'] },
  { char: '👋', name: 'waving hand', category: 'smileys', keywords: ['wave', 'hello', 'hi', 'bye'] },
  { char: '🤚', name: 'raised back of hand', category: 'smileys', keywords: ['back of hand'] },
  { char: '🖐️', name: 'hand with fingers splayed', category: 'smileys', keywords: ['hand', 'five'] },
  { char: '✋', name: 'raised hand', category: 'smileys', keywords: ['stop', 'high five'] },
  { char: '🖖', name: 'vulcan salute', category: 'smileys', keywords: ['spock', 'star trek'] },
  { char: '👌', name: 'OK hand', category: 'smileys', keywords: ['ok', 'perfect'] },
  { char: '🤏', name: 'pinching hand', category: 'smileys', keywords: ['small', 'pinch'] },
  { char: '✌️', name: 'victory hand', category: 'smileys', keywords: ['peace', 'victory'] },
  { char: '🤞', name: 'crossed fingers', category: 'smileys', keywords: ['luck', 'hope'] },
  { char: '🤟', name: 'love-you gesture', category: 'smileys', keywords: ['love', 'ily'] },
  { char: '🤘', name: 'sign of the horns', category: 'smileys', keywords: ['rock on', 'horns'] },
  { char: '🤙', name: 'call me hand', category: 'smileys', keywords: ['call', 'phone', 'shaka'] },
  { char: '👈', name: 'backhand index pointing left', category: 'smileys', keywords: ['left', 'index'] },
  { char: '👉', name: 'backhand index pointing right', category: 'smileys', keywords: ['right', 'index'] },
  { char: '👆', name: 'backhand index pointing up', category: 'smileys', keywords: ['up', 'index'] },
  { char: '🖕', name: 'middle finger', category: 'smileys', keywords: ['rude', 'middle finger'] },
  { char: '👇', name: 'backhand index pointing down', category: 'smileys', keywords: ['down', 'index'] },
  { char: '☝️', name: 'index pointing up', category: 'smileys', keywords: ['up', 'index'] },
  { char: '👍', name: 'thumbs up', category: 'smileys', keywords: ['good', 'ok', 'approve', 'like'] },
  { char: '👎', name: 'thumbs down', category: 'smileys', keywords: ['bad', 'no', 'dislike'] },
  { char: '✊', name: 'raised fist', category: 'smileys', keywords: ['fist', 'power'] },
  { char: '👊', name: 'oncoming fist', category: 'smileys', keywords: ['punch', 'fist', 'bump'] },
  { char: '🤛', name: 'left-facing fist', category: 'smileys', keywords: ['fist', 'bump'] },
  { char: '🤜', name: 'right-facing fist', category: 'smileys', keywords: ['fist', 'bump'] },
  { char: '👏', name: 'clapping hands', category: 'smileys', keywords: ['clap', 'applause'] },
  { char: '🙌', name: 'raising hands', category: 'smileys', keywords: ['praise', 'hooray'] },
  { char: '👐', name: 'open hands', category: 'smileys', keywords: ['open', 'hug'] },
  { char: '🤲', name: 'palms up together', category: 'smileys', keywords: ['pray', 'offer'] },
  { char: '🤝', name: 'handshake', category: 'smileys', keywords: ['agree', 'deal', 'shake'] },
  { char: '🙏', name: 'folded hands', category: 'smileys', keywords: ['pray', 'thanks', 'please'] },
  { char: '💪', name: 'flexed biceps', category: 'smileys', keywords: ['strong', 'flex', 'muscle'] },
  { char: '🦾', name: 'mechanical arm', category: 'smileys', keywords: ['robot', 'strong'] },
  { char: '🦵', name: 'leg', category: 'smileys', keywords: ['leg', 'kick'] },
  { char: '🦿', name: 'mechanical leg', category: 'smileys', keywords: ['robot', 'leg'] },
  { char: '🦴', name: 'bone', category: 'smileys', keywords: ['bone', 'skeleton'] },

  // Animals & Nature
  { char: '🐶', name: 'dog face', category: 'animals', keywords: ['dog', 'puppy', 'pet'] },
  { char: '🐱', name: 'cat face', category: 'animals', keywords: ['cat', 'kitty', 'pet'] },
  { char: '🐭', name: 'mouse face', category: 'animals', keywords: ['mouse', 'rodent'] },
  { char: '🐹', name: 'hamster face', category: 'animals', keywords: ['hamster', 'pet'] },
  { char: '🐰', name: 'rabbit face', category: 'animals', keywords: ['rabbit', 'bunny', 'pet'] },
  { char: '🦊', name: 'fox face', category: 'animals', keywords: ['fox'] },
  { char: '🐻', name: 'bear face', category: 'animals', keywords: ['bear'] },
  { char: '🐼', name: 'panda face', category: 'animals', keywords: ['panda'] },
  { char: '🐨', name: 'koala', category: 'animals', keywords: ['koala'] },
  { char: '🐯', name: 'tiger face', category: 'animals', keywords: ['tiger'] },
  { char: '🦁', name: 'lion face', category: 'animals', keywords: ['lion'] },
  { char: '🐮', name: 'cow face', category: 'animals', keywords: ['cow'] },
  { char: '🐷', name: 'pig face', category: 'animals', keywords: ['pig'] },
  { char: '🐽', name: 'pig nose', category: 'animals', keywords: ['pig', 'nose'] },
  { char: '🐸', name: 'frog face', category: 'animals', keywords: ['frog'] },
  { char: '🐵', name: 'monkey face', category: 'animals', keywords: ['monkey'] },
  { char: '🙈', name: 'see-no-evil monkey', category: 'animals', keywords: ['monkey', 'eyes'] },
  { char: '🙉', name: 'hear-no-evil monkey', category: 'animals', keywords: ['monkey', 'ears'] },
  { char: '🙊', name: 'speak-no-evil monkey', category: 'animals', keywords: ['monkey', 'mouth'] },
  { char: '🐒', name: 'monkey', category: 'animals', keywords: ['monkey'] },
  { char: '🐔', name: 'chicken', category: 'animals', keywords: ['chicken'] },
  { char: '🐧', name: 'penguin', category: 'animals', keywords: ['penguin'] },
  { char: '🐦', name: 'bird', category: 'animals', keywords: ['bird'] },
  { char: '🐤', name: 'baby chick', category: 'animals', keywords: ['chick', 'bird'] },
  { char: '🐣', name: 'hatching chick', category: 'animals', keywords: ['chick', 'egg'] },
  { char: '🐥', name: 'front-facing baby chick', category: 'animals', keywords: ['chick', 'bird'] },
  { char: '🦆', name: 'duck', category: 'animals', keywords: ['duck'] },
  { char: '🦅', name: 'eagle', category: 'animals', keywords: ['eagle', 'bird'] },
  { char: '🦉', name: 'owl', category: 'animals', keywords: ['owl', 'bird'] },
  { char: '🦇', name: 'bat', category: 'animals', keywords: ['bat', 'vampire'] },
  { char: '🐺', name: 'wolf face', category: 'animals', keywords: ['wolf'] },
  { char: '🐗', name: 'boar', category: 'animals', keywords: ['boar', 'pig'] },
  { char: '🐴', name: 'horse face', category: 'animals', keywords: ['horse'] },
  { char: '🦄', name: 'unicorn face', category: 'animals', keywords: ['unicorn', 'magic'] },
  { char: '🐝', name: 'honeybee', category: 'animals', keywords: ['bee', 'bug', 'insect'] },
  { char: '🐛', name: 'bug', category: 'animals', keywords: ['bug', 'insect'] },
  { char: '🦋', name: 'butterfly', category: 'animals', keywords: ['butterfly', 'bug'] },
  { char: '🐌', name: 'snail', category: 'animals', keywords: ['snail', 'bug'] },
  { char: '🐞', name: 'lady beetle', category: 'animals', keywords: ['ladybug', 'bug'] },
  { char: '🐜', name: 'ant', category: 'animals', keywords: ['ant', 'bug'] },
  { char: '🦗', name: 'cricket', category: 'animals', keywords: ['cricket', 'bug'] },
  { char: '🕷️', name: 'spider', category: 'animals', keywords: ['spider', 'bug'] },
  { char: '🦂', name: 'scorpion', category: 'animals', keywords: ['scorpion', 'bug'] },
  { char: '🐢', name: 'turtle', category: 'animals', keywords: ['turtle'] },
  { char: '🐍', name: 'snake', category: 'animals', keywords: ['snake'] },
  { char: '🦎', name: 'lizard', category: 'animals', keywords: ['lizard'] },
  { char: '🦖', name: 'T-Rex', category: 'animals', keywords: ['dino', 'dinosaur'] },
  { char: '🦕', name: 'sauropod', category: 'animals', keywords: ['dino', 'dinosaur'] },
  { char: '🐙', name: 'octopus', category: 'animals', keywords: ['octopus'] },
  { char: '🦑', name: 'squid', category: 'animals', keywords: ['squid'] },
  { char: '🦐', name: 'shrimp', category: 'animals', keywords: ['shrimp'] },
  { char: '🦞', name: 'lobster', category: 'animals', keywords: ['lobster'] },
  { char: '🦀', name: 'crab', category: 'animals', keywords: ['crab'] },
  { char: '🐡', name: 'blowfish', category: 'animals', keywords: ['fish'] },
  { char: '🐠', name: 'tropical fish', category: 'animals', keywords: ['fish'] },
  { char: '🐟', name: 'fish', category: 'animals', keywords: ['fish'] },
  { char: '🐬', name: 'dolphin', category: 'animals', keywords: ['dolphin'] },
  { char: '🐳', name: 'spouting whale', category: 'animals', keywords: ['whale'] },
  { char: '🐋', name: 'whale', category: 'animals', keywords: ['whale'] },
  { char: '🦈', name: 'shark', category: 'animals', keywords: ['shark'] },
  { char: '🐊', name: 'crocodile', category: 'animals', keywords: ['crocodile'] },
  { char: '🐅', name: 'tiger', category: 'animals', keywords: ['tiger'] },
  { char: '🐆', name: 'leopard', category: 'animals', keywords: ['leopard'] },
  { char: '🦓', name: 'zebra', category: 'animals', keywords: ['zebra'] },
  { char: '🦍', name: 'gorilla', category: 'animals', keywords: ['gorilla'] },
  { char: '🦧', name: 'orangutan', category: 'animals', keywords: ['orangutan', 'monkey'] },
  { char: '🐘', name: 'elephant', category: 'animals', keywords: ['elephant'] },
  { char: '🦛', name: 'hippopotamus', category: 'animals', keywords: ['hippo'] },
  { char: '🦏', name: 'rhinoceros', category: 'animals', keywords: ['rhino'] },
  { char: '🐪', name: 'camel', category: 'animals', keywords: ['camel'] },
  { char: '🐫', name: 'two-hump camel', category: 'animals', keywords: ['camel'] },
  { char: '🦒', name: 'giraffe', category: 'animals', keywords: ['giraffe'] },
  { char: '🦘', name: 'kangaroo', category: 'animals', keywords: ['kangaroo'] },
  { char: '🐃', name: 'water buffalo', category: 'animals', keywords: ['buffalo'] },
  { char: '🐂', name: 'ox', category: 'animals', keywords: ['ox'] },
  { char: '🐄', name: 'cow', category: 'animals', keywords: ['cow'] },
  { char: '🐎', name: 'horse', category: 'animals', keywords: ['horse'] },
  { char: '🐖', name: 'pig', category: 'animals', keywords: ['pig'] },
  { char: '🐏', name: 'ram', category: 'animals', keywords: ['ram'] },
  { char: '🐑', name: 'ewe', category: 'animals', keywords: ['sheep'] },
  { char: '🦙', name: 'llama', category: 'animals', keywords: ['llama'] },
  { char: '🐐', name: 'goat', category: 'animals', keywords: ['goat'] },
  { char: '🦌', name: 'deer', category: 'animals', keywords: ['deer'] },
  { char: '🐕', name: 'dog', category: 'animals', keywords: ['dog'] },
  { char: '🐩', name: 'poodle', category: 'animals', keywords: ['dog', 'poodle'] },
  { char: '🦮', name: 'guide dog', category: 'animals', keywords: ['dog', 'service'] },
  { char: '🐈', name: 'cat', category: 'animals', keywords: ['cat'] },
  { char: '🐓', name: 'rooster', category: 'animals', keywords: ['chicken', 'rooster'] },
  { char: '🦃', name: 'turkey', category: 'animals', keywords: ['turkey'] },
  { char: '🦚', name: 'peacock', category: 'animals', keywords: ['peacock'] },
  { char: '🦢', name: 'swan', category: 'animals', keywords: ['swan', 'bird'] },
  { char: '🦩', name: 'flamingo', category: 'animals', keywords: ['flamingo', 'bird'] },
  { char: '🕊️', name: 'dove', category: 'animals', keywords: ['dove', 'peace', 'bird'] },
  { char: '🐇', name: 'rabbit', category: 'animals', keywords: ['rabbit', 'bunny'] },
  { char: '🦝', name: 'raccoon', category: 'animals', keywords: ['raccoon'] },
  { char: '🦨', name: 'skunk', category: 'animals', keywords: ['skunk'] },
  { char: '🦡', name: 'badger', category: 'animals', keywords: ['badger'] },
  { char: '🦦', name: 'otter', category: 'animals', keywords: ['otter'] },
  { char: '🦥', name: 'sloth', category: 'animals', keywords: ['sloth'] },
  { char: '🐁', name: 'mouse', category: 'animals', keywords: ['mouse', 'rodent'] },
  { char: '🐀', name: 'rat', category: 'animals', keywords: ['rat', 'rodent'] },
  { char: '🐿️', name: 'chipmunk', category: 'animals', keywords: ['chipmunk'] },
  { char: '🦔', name: 'hedgehog', category: 'animals', keywords: ['hedgehog'] },

  // Food & Drink
  { char: '🍏', name: 'green apple', category: 'food', keywords: ['apple', 'fruit'] },
  { char: '🍎', name: 'red apple', category: 'food', keywords: ['apple', 'fruit'] },
  { char: '🍐', name: 'pear', category: 'food', keywords: ['pear', 'fruit'] },
  { char: '🍊', name: 'tangerine', category: 'food', keywords: ['orange', 'fruit'] },
  { char: '🍋', name: 'lemon', category: 'food', keywords: ['lemon', 'fruit', 'sour'] },
  { char: '🍌', name: 'banana', category: 'food', keywords: ['banana', 'fruit'] },
  { char: '🍉', name: 'watermelon', category: 'food', keywords: ['watermelon', 'fruit'] },
  { char: '🍇', name: 'grapes', category: 'food', keywords: ['grapes', 'fruit'] },
  { char: '🍓', name: 'strawberry', category: 'food', keywords: ['strawberry', 'fruit'] },
  { char: '🍈', name: 'melon', category: 'food', keywords: ['melon', 'fruit'] },
  { char: '🍒', name: 'cherries', category: 'food', keywords: ['cherries', 'fruit'] },
  { char: '🍑', name: 'peach', category: 'food', keywords: ['peach', 'fruit'] },
  { char: '🥭', name: 'mango', category: 'food', keywords: ['mango', 'fruit'] },
  { char: '🍍', name: 'pineapple', category: 'food', keywords: ['pineapple', 'fruit'] },
  { char: '🥥', name: 'coconut', category: 'food', keywords: ['coconut', 'fruit'] },
  { char: '🥝', name: 'kiwi fruit', category: 'food', keywords: ['kiwi', 'fruit'] },
  { char: '🍅', name: 'tomato', category: 'food', keywords: ['tomato', 'fruit', 'vegetable'] },
  { char: '🍆', name: 'eggplant', category: 'food', keywords: ['eggplant', 'vegetable'] },
  { char: '🥑', name: 'avocado', category: 'food', keywords: ['avocado', 'fruit'] },
  { char: '🥦', name: 'broccoli', category: 'food', keywords: ['broccoli', 'vegetable'] },
  { char: '🥬', name: 'leafy green', category: 'food', keywords: ['lettuce', 'vegetable'] },
  { char: '🥒', name: 'cucumber', category: 'food', keywords: ['cucumber', 'vegetable'] },
  { char: '🌶️', name: 'hot pepper', category: 'food', keywords: ['pepper', 'spicy'] },
  { char: '🌽', name: 'ear of corn', category: 'food', keywords: ['corn', 'vegetable'] },
  { char: '🥕', name: 'carrot', category: 'food', keywords: ['carrot', 'vegetable'] },
  { char: '🧄', name: 'garlic', category: 'food', keywords: ['garlic', 'vegetable'] },
  { char: '🧅', name: 'onion', category: 'food', keywords: ['onion', 'vegetable'] },
  { char: '🥔', name: 'potato', category: 'food', keywords: ['potato', 'vegetable'] },
  { char: '🍠', name: 'roasted sweet potato', category: 'food', keywords: ['sweet potato', 'vegetable'] },
  { char: '🥐', name: 'croissant', category: 'food', keywords: ['croissant', 'bread', 'pastry'] },
  { char: '🥯', name: 'bagel', category: 'food', keywords: ['bagel', 'bread'] },
  { char: '🍞', name: 'bread', category: 'food', keywords: ['bread', 'toast'] },
  { char: '🥖', name: 'baguette bread', category: 'food', keywords: ['baguette', 'bread'] },
  { char: '🥨', name: 'pretzel', category: 'food', keywords: ['pretzel', 'snack'] },
  { char: '🧀', name: 'cheese wedge', category: 'food', keywords: ['cheese'] },
  { char: '🥚', name: 'egg', category: 'food', keywords: ['egg'] },
  { char: '🍳', name: 'cooking', category: 'food', keywords: ['egg', 'breakfast', 'fry'] },
  { char: '🧈', name: 'butter', category: 'food', keywords: ['butter'] },
  { char: '🥞', name: 'pancakes', category: 'food', keywords: ['pancakes', 'breakfast'] },
  { char: '🧇', name: 'waffle', category: 'food', keywords: ['waffle', 'breakfast'] },
  { char: '🥓', name: 'bacon', category: 'food', keywords: ['bacon', 'breakfast'] },
  { char: '🥩', name: 'cut of meat', category: 'food', keywords: ['meat', 'steak'] },
  { char: '🍗', name: 'poultry leg', category: 'food', keywords: ['chicken', 'meat'] },
  { char: '🍖', name: 'meat on bone', category: 'food', keywords: ['meat'] },
  { char: '🌭', name: 'hot dog', category: 'food', keywords: ['hot dog'] },
  { char: '🍔', name: 'hamburger', category: 'food', keywords: ['hamburger', 'burger'] },
  { char: '🍟', name: 'french fries', category: 'food', keywords: ['fries', 'snack'] },
  { char: '🍕', name: 'pizza', category: 'food', keywords: ['pizza'] },
  { char: '🥪', name: 'sandwich', category: 'food', keywords: ['sandwich'] },
  { char: '🥙', name: 'stuffed flatbread', category: 'food', keywords: ['pita', 'gyros'] },
  { char: '🧆', name: 'falafel', category: 'food', keywords: ['falafel'] },
  { char: '🌮', name: 'taco', category: 'food', keywords: ['taco'] },
  { char: '🌯', name: 'burrito', category: 'food', keywords: ['burrito'] },
  { char: '🥗', name: 'green salad', category: 'food', keywords: ['salad', 'vegetable'] },
  { char: '🥘', name: 'shallow pan of food', category: 'food', keywords: ['paella', 'cooking'] },
  { char: '🥫', name: 'canned food', category: 'food', keywords: ['can', 'food'] },
  { char: '🍝', name: 'spaghetti', category: 'food', keywords: ['spaghetti', 'pasta'] },
  { char: '🍜', name: 'steaming bowl', category: 'food', keywords: ['ramen', 'noodles'] },
  { char: '🍲', name: 'pot of food', category: 'food', keywords: ['stew', 'soup'] },
  { char: '🍛', name: 'curry rice', category: 'food', keywords: ['curry', 'rice'] },
  { char: '🍣', name: 'sushi', category: 'food', keywords: ['sushi'] },
  { char: '🍱', name: 'bento box', category: 'food', keywords: ['bento', 'box'] },
  { char: '🥟', name: 'dumpling', category: 'food', keywords: ['dumpling'] },
  { char: '🦪', name: 'oyster', category: 'food', keywords: ['oyster', 'seafood'] },
  { char: '🍤', name: 'fried shrimp', category: 'food', keywords: ['shrimp', 'seafood'] },
  { char: '🍙', name: 'rice ball', category: 'food', keywords: ['rice ball'] },
  { char: '🍚', name: 'cooked rice', category: 'food', keywords: ['rice'] },
  { char: '🍘', name: 'rice cracker', category: 'food', keywords: ['rice cracker'] },
  { char: '🍥', name: 'fish cake with swirl', category: 'food', keywords: ['fish cake'] },
  { char: '🥠', name: 'fortune cookie', category: 'food', keywords: ['fortune cookie'] },
  { char: '🥮', name: 'moon cake', category: 'food', keywords: ['moon cake'] },
  { char: '🍢', name: 'oden', category: 'food', keywords: ['oden'] },
  { char: '🍡', name: 'dango', category: 'food', keywords: ['dango'] },
  { char: '🍧', name: 'shaved ice', category: 'food', keywords: ['shaved ice'] },
  { char: '🍨', name: 'ice cream', category: 'food', keywords: ['ice cream', 'dessert'] },
  { char: '🍦', name: 'soft serve', category: 'food', keywords: ['ice cream', 'dessert'] },
  { char: '🥧', name: 'pie', category: 'food', keywords: ['pie', 'dessert'] },
  { char: '🧁', name: 'cupcake', category: 'food', keywords: ['cupcake', 'dessert'] },
  { char: '🍰', name: 'shortcake', category: 'food', keywords: ['cake', 'dessert'] },
  { char: '🎂', name: 'birthday cake', category: 'food', keywords: ['cake', 'dessert', 'birthday'] },
  { char: '🍮', name: 'custard', category: 'food', keywords: ['pudding', 'dessert'] },
  { char: '🍭', name: 'lollipop', category: 'food', keywords: ['lollipop', 'candy'] },
  { char: '🍬', name: 'candy', category: 'food', keywords: ['candy'] },
  { char: '🍫', name: 'chocolate bar', category: 'food', keywords: ['chocolate'] },
  { char: '🍿', name: 'popcorn', category: 'food', keywords: ['popcorn', 'snack'] },
  { char: '🍩', name: 'doughnut', category: 'food', keywords: ['donut', 'dessert'] },
  { char: '🍪', name: 'cookie', category: 'food', keywords: ['cookie', 'dessert'] },
  { char: '🌰', name: 'chestnut', category: 'food', keywords: ['chestnut'] },
  { char: '🥜', name: 'peanuts', category: 'food', keywords: ['peanuts', 'snack'] },
  { char: '🍯', name: 'honey pot', category: 'food', keywords: ['honey'] },
  { char: '🥛', name: 'glass of milk', category: 'food', keywords: ['milk'] },
  { char: '🍼', name: 'baby bottle', category: 'food', keywords: ['baby', 'bottle'] },
  { char: '☕', name: 'hot beverage', category: 'food', keywords: ['coffee', 'tea'] },
  { char: '🍵', name: 'teacup without handle', category: 'food', keywords: ['tea'] },
  { char: '🧃', name: 'beverage box', category: 'food', keywords: ['juice'] },
  { char: '🥤', name: 'cup with straw', category: 'food', keywords: ['soda', 'drink'] },
  { char: '🍶', name: 'sake', category: 'food', keywords: ['sake', 'drink'] },
  { char: '🍺', name: 'beer mug', category: 'food', keywords: ['beer', 'drink'] },
  { char: '🍻', name: 'clinking beer mugs', category: 'food', keywords: ['beer', 'drink', 'toast'] },
  { char: '🥂', name: 'clinking glasses', category: 'food', keywords: ['wine', 'champagne', 'toast'] },
  { char: '🍷', name: 'wine glass', category: 'food', keywords: ['wine', 'drink'] },
  { char: '🥃', name: 'tumbler glass', category: 'food', keywords: ['whiskey', 'drink'] },
  { char: '🍸', name: 'cocktail glass', category: 'food', keywords: ['cocktail', 'drink'] },
  { char: '🍹', name: 'tropical drink', category: 'food', keywords: ['cocktail', 'drink', 'tropical'] },
  { char: '🧉', name: 'mate', category: 'food', keywords: ['mate', 'drink'] },
  { char: '🍾', name: 'bottle with popping cork', category: 'food', keywords: ['champagne', 'celebrate'] },

  // Symbols
  { char: '❤️', name: 'red heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '🧡', name: 'orange heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '💛', name: 'yellow heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '💚', name: 'green heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '💙', name: 'blue heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '💜', name: 'purple heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '🖤', name: 'black heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '🤍', name: 'white heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '🤎', name: 'brown heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '💔', name: 'broken heart', category: 'symbols', keywords: ['heart', 'broken'] },
  { char: '❣️', 'name': 'heart exclamation', category: 'symbols', keywords: ['heart', 'exclamation'] },
  { char: '💕', name: 'two hearts', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '💞', name: 'revolving hearts', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '💓', name: 'beating heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '💗', name: 'growing heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '💖', name: 'sparkling heart', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '💘', name: 'heart with arrow', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '💝', name: 'heart with ribbon', category: 'symbols', keywords: ['heart', 'gift'] },
  { char: '💟', name: 'heart decoration', category: 'symbols', keywords: ['heart', 'love'] },
  { char: '✨', name: 'sparkles', category: 'symbols', keywords: ['sparkle', 'magic', 'shiny'] },
  { char: '🔥', name: 'fire', category: 'symbols', keywords: ['fire', 'hot', 'lit'] },
  { char: '💯', name: 'hundred points', category: 'symbols', keywords: ['100', 'perfect', 'score'] },
  { char: '✅', name: 'check mark button', category: 'symbols', keywords: ['check', 'ok', 'yes'] },
  { char: '⭐', name: 'star', category: 'symbols', keywords: ['star', 'favor'] },
  // Activities
  { char: '⚽', name: 'soccer ball', category: 'activities', keywords: ['soccer', 'ball', 'sport'] },
  { char: '🏀', name: 'basketball', category: 'activities', keywords: ['basketball', 'ball', 'sport'] },
  { char: '🏈', name: 'american football', category: 'activities', keywords: ['football', 'sport'] },
  { char: '⚾', name: 'baseball', category: 'activities', keywords: ['baseball', 'sport'] },
  { char: '🎾', name: 'tennis', category: 'activities', keywords: ['tennis', 'sport'] },
  { char: '🏐', name: 'volleyball', category: 'activities', keywords: ['volleyball', 'sport'] },
  { char: '🏉', name: 'rugby football', category: 'activities', keywords: ['rugby', 'sport'] },
  { char: '🎱', name: 'pool 8 ball', category: 'activities', keywords: ['pool', '8ball', 'sport'] },
  { char: '🏓', name: 'ping pong', category: 'activities', keywords: ['ping pong', 'sport'] },
  { char: '🏸', name: 'badminton', category: 'activities', keywords: ['badminton', 'sport'] },
  { char: '🥅', name: 'goal net', category: 'activities', keywords: ['goal', 'net', 'sport'] },
  { char: '⛳', name: 'flag in hole', category: 'activities', keywords: ['golf', 'sport'] },
  { char: '⛸️', name: 'ice skate', category: 'activities', keywords: ['skate', 'sport'] },
  { char: '🎣', name: 'fishing pole', category: 'activities', keywords: ['fish', 'fishing'] },
  { char: '🎯', name: 'bullseye', category: 'activities', keywords: ['darts', 'target'] },
  { char: '🎮', name: 'video game', category: 'activities', keywords: ['game', 'play', 'console'] },
  { char: '🕹️', name: 'joystick', category: 'activities', keywords: ['game', 'play'] },
  { char: '🎲', name: 'game die', category: 'activities', keywords: ['dice', 'game'] },
  { char: '🧩', name: 'puzzle piece', category: 'activities', keywords: ['puzzle', 'game'] },
  { char: '♟️', name: 'chess pawn', category: 'activities', keywords: ['chess', 'game'] },
  { char: '🎭', name: 'performing arts', category: 'activities', keywords: ['theater', 'mask', 'drama'] },
  { char: '🎨', name: 'artist palette', category: 'activities', keywords: ['art', 'paint', 'draw'] },
  { char: '🧵', name: 'thread', category: 'activities', keywords: ['sew', 'knit'] },
  { char: '🧶', name: 'yarn', category: 'activities', keywords: ['sew', 'knit'] },

  // Travel & Places
  { char: '🌍', name: 'globe showing Europe-Africa', category: 'travel', keywords: ['earth', 'globe', 'world'] },
  { char: '🌎', name: 'globe showing Americas', category: 'travel', keywords: ['earth', 'globe', 'world'] },
  { char: '🌏', name: 'globe showing Asia-Australia', category: 'travel', keywords: ['earth', 'globe', 'world'] },
  { char: '🌐', name: 'globe with meridians', category: 'travel', keywords: ['internet', 'world'] },
  { char: '🗺️', name: 'world map', category: 'travel', keywords: ['map', 'travel'] },
  { char: '🗾', name: 'map of Japan', category: 'travel', keywords: ['japan', 'map'] },
  { char: '🧭', name: 'compass', category: 'travel', keywords: ['compass', 'direction'] },
  { char: '🏔️', name: 'snow-capped mountain', category: 'travel', keywords: ['mountain', 'snow'] },
  { char: '⛰️', name: 'mountain', category: 'travel', keywords: ['mountain'] },
  { char: '🌋', name: 'volcano', category: 'travel', keywords: ['volcano'] },
  { char: '🗻', name: 'mount fuji', category: 'travel', keywords: ['mountain', 'fuji'] },
  { char: '🏕️', name: 'camping', category: 'travel', keywords: ['camp', 'tent'] },
  { char: '🏖️', name: 'beach with umbrella', category: 'travel', keywords: ['beach', 'summer'] },
  { char: '🏜️', name: 'desert', category: 'travel', keywords: ['desert'] },
  { char: '🏝️', name: 'desert island', category: 'travel', keywords: ['island', 'beach'] },
  { char: '🏞️', name: 'national park', category: 'travel', keywords: ['park', 'nature'] },
  { char: '🏟️', name: 'stadium', category: 'travel', keywords: ['stadium', 'sport'] },
  { char: '🏛️', name: 'classical building', category: 'travel', keywords: ['museum', 'building'] },
  { char: '🏗️', name: 'building construction', category: 'travel', keywords: ['construction'] },
  { char: '🧱', name: 'brick', category: 'travel', keywords: ['brick', 'building'] },
  { char: '🏘️', name: 'houses', category: 'travel', keywords: ['homes', 'house'] },
  { char: '🏚️', name: 'derelict house', category: 'travel', keywords: ['haunted', 'house'] },
  { char: '🏠', name: 'house', category: 'travel', keywords: ['home', 'house'] },
  { char: '🏡', name: 'house with garden', category: 'travel', keywords: ['home', 'house'] },
  { char: '🏢', name: 'office building', category: 'travel', keywords: ['office', 'work'] },
  { char: '🏣', name: 'Japanese post office', category: 'travel', keywords: ['post'] },
  { char: '🏤', name: 'post office', category: 'travel', keywords: ['post'] },
  { char: '🏥', name: 'hospital', category: 'travel', keywords: ['hospital', 'doctor'] },
  { char: '🏦', name: 'bank', category: 'travel', keywords: ['bank', 'money'] },
  { char: '🏨', name: 'hotel', category: 'travel', keywords: ['hotel'] },
  { char: '🏩', name: 'love hotel', category: 'travel', keywords: ['hotel', 'love'] },
  { char: '🏪', name: 'convenience store', category: 'travel', keywords: ['store', 'shop'] },
  { char: '🏫', name: 'school', category: 'travel', keywords: ['school', 'education'] },
  { char: '🏬', name: 'department store', category: 'travel', keywords: ['store', 'shop'] },
  { char: '🏭', name: 'factory', category: 'travel', keywords: ['factory', 'industrial'] },
  { char: '🏯', name: 'Japanese castle', category: 'travel', keywords: ['castle'] },
  { char: '🏰', name: 'castle', category: 'travel', keywords: ['castle'] },
  { char: '💒', name: 'wedding', category: 'travel', keywords: ['wedding', 'marriage'] },
  { char: '🗼', name: 'Tokyo tower', category: 'travel', keywords: ['tower'] },
  { char: '🗽', name: 'Statue of Liberty', category: 'travel', keywords: ['liberty', 'statue'] },
  { char: '⛪', name: 'church', category: 'travel', keywords: ['church', 'religion'] },
  { char: '🕌', name: 'mosque', category: 'travel', keywords: ['mosque', 'religion'] },
  { char: '🕋', name: 'kaaba', category: 'travel', keywords: ['kaaba', 'religion'] },
  { char: '🕍', name: 'synagogue', category: 'travel', keywords: ['synagogue', 'religion'] },
  { char: '⛩️', name: 'shinto shrine', category: 'travel', keywords: ['shrine', 'shinto'] },
  { char: '⛲', name: 'fountain', category: 'travel', keywords: ['fountain'] },
  { char: '⛺', name: 'tent', category: 'travel', keywords: ['tent', 'camp'] },
  { char: '🌁', name: 'foggy', category: 'travel', keywords: ['fog', 'weather'] },
  { char: '🌃', name: 'night with stars', category: 'travel', keywords: ['night', 'stars'] },
  { char: '🏙️', name: 'cityscape', category: 'travel', keywords: ['city'] },
  { char: '🌄', name: 'sunrise over mountains', category: 'travel', keywords: ['sunrise', 'morning'] },
  { char: '🌅', name: 'sunrise', category: 'travel', keywords: ['sunrise', 'morning'] },
  { char: '🌆', name: 'cityscape at dusk', category: 'travel', keywords: ['sunset', 'evening'] },
  { char: '🌇', name: 'sunset', category: 'travel', keywords: ['sunset', 'evening'] },
  { char: '🌉', name: 'bridge at night', category: 'travel', keywords: ['bridge', 'night'] },
  { char: '🌌', name: 'milky way', category: 'travel', keywords: ['stars', 'galaxy'] },
  { char: '🎠', name: 'carousel horse', category: 'travel', keywords: ['carousel'] },
  { char: '🎡', name: 'ferris wheel', category: 'travel', keywords: ['ferris wheel', 'carnival'] },
  { char: '🎢', name: 'roller coaster', category: 'travel', keywords: ['roller coaster', 'park'] },
  { char: '🚂', name: 'locomotive', category: 'travel', keywords: ['train', 'engine'] },
  { char: '🚃', name: 'railway car', category: 'travel', keywords: ['train'] },
  { char: '🚄', name: 'high-speed train', category: 'travel', keywords: ['train'] },
  { char: '🚅', name: 'bullet train', category: 'travel', keywords: ['train'] },
  { char: '🚆', name: 'train', category: 'travel', keywords: ['train'] },
  { char: '🚇', name: 'metro', category: 'travel', keywords: ['train', 'subway'] },
  { char: '🚈', name: 'light rail', category: 'travel', keywords: ['train'] },
  { char: '🚉', name: 'station', category: 'travel', keywords: ['train', 'station'] },
  { char: '🚊', name: 'tram', category: 'travel', keywords: ['train'] },
  { char: '🚝', name: 'monorail', category: 'travel', keywords: ['train'] },
  { char: '🚞', name: 'mountain railway', category: 'travel', keywords: ['train'] },
  { char: '🚋', name: 'tram car', category: 'travel', keywords: ['train'] },
  { char: '🚌', name: 'bus', category: 'travel', keywords: ['bus', 'travel'] },
  { char: '🚍', name: 'oncoming bus', category: 'travel', keywords: ['bus'] },
  { char: '🚎', name: 'trolleybus', category: 'travel', keywords: ['bus'] },
  { char: '🚐', name: 'minibus', category: 'travel', keywords: ['bus'] },
  { char: '🚑', name: 'ambulance', category: 'travel', keywords: ['ambulance', 'medical'] },
  { char: '🚒', name: 'fire engine', category: 'travel', keywords: ['fire', 'engine'] },
  { char: '🚓', name: 'police car', category: 'travel', keywords: ['police', 'car'] },
  { char: '🚔', name: 'oncoming police car', category: 'travel', keywords: ['police', 'car'] },
  { char: '🚕', name: 'taxi', category: 'travel', keywords: ['taxi', 'car'] },
  { char: '🚖', name: 'oncoming taxi', category: 'travel', keywords: ['taxi', 'car'] },
  { char: '🚗', name: 'automobile', category: 'travel', keywords: ['car', 'travel'] },
  { char: '🚘', name: 'oncoming automobile', category: 'travel', keywords: ['car'] },
  { char: '🚙', name: 'sport utility vehicle', category: 'travel', keywords: ['suv', 'car'] },
  { char: '🚚', name: 'delivery truck', category: 'travel', keywords: ['truck', 'delivery'] },
  { char: '🚛', name: 'articulated lorry', category: 'travel', keywords: ['truck'] },
  { char: '🚜', name: 'tractor', category: 'travel', keywords: ['tractor', 'farm'] },
  { char: '🏎️', name: 'racing car', category: 'travel', keywords: ['race', 'car'] },
  { char: '🏍️', name: 'motorcycle', category: 'travel', keywords: ['motorcycle', 'bike'] },
  { char: '🚲', name: 'bicycle', category: 'travel', keywords: ['bike', 'bicycle'] },
  { char: '🛴', name: 'kick scooter', category: 'travel', keywords: ['scooter'] },
  { char: '🚏', name: 'bus stop', category: 'travel', keywords: ['bus', 'stop'] },
  { char: '🛣️', name: 'motorway', category: 'travel', keywords: ['road', 'highway'] },
  { char: '🛤️', name: 'railway track', category: 'travel', keywords: ['rail', 'train'] },
  { char: '⛽', name: 'fuel pump', category: 'travel', keywords: ['gas', 'fuel'] },
  { char: '🚨', name: 'police car light', category: 'travel', keywords: ['police', 'siren'] },
  { char: '🚥', name: 'horizontal traffic light', category: 'travel', keywords: ['traffic', 'light'] },
  { char: '🚦', name: 'vertical traffic light', category: 'travel', keywords: ['traffic', 'light'] },
  { char: '🛑', name: 'stop sign', category: 'travel', keywords: ['stop'] },
  { char: '🚧', name: 'construction', category: 'travel', keywords: ['construction'] },
  { char: '⚓', name: 'anchor', category: 'travel', keywords: ['anchor', 'ship'] },
  { char: '⛵', name: 'sailboat', category: 'travel', keywords: ['boat', 'sail'] },
  { char: '🚤', name: 'speedboat', category: 'travel', keywords: ['boat'] },
  { char: '🛳️', name: 'passenger ship', category: 'travel', keywords: ['ship', 'cruise'] },
  { char: '⛴️', name: 'ferry', category: 'travel', keywords: ['ferry', 'boat'] },
  { char: '🚢', name: 'ship', category: 'travel', keywords: ['ship'] },
  { char: '✈️', name: 'airplane', category: 'travel', keywords: ['plane', 'airplane'] },
  { char: '🛩️', name: 'small airplane', category: 'travel', keywords: ['plane'] },
  { char: '🛫', name: 'airplane departure', category: 'travel', keywords: ['plane', 'takeoff'] },
  { char: '🛬', name: 'airplane arrival', category: 'travel', keywords: ['plane', 'landing'] },
  { char: '💺', name: 'seat', category: 'travel', keywords: ['seat', 'airplane'] },
  { char: '🚁', name: 'helicopter', category: 'travel', keywords: ['helicopter'] },
  { char: '🚟', name: 'suspension railway', category: 'travel', keywords: ['rail'] },
  { char: '🚠', name: 'mountain cableway', category: 'travel', keywords: ['cableway'] },
  { char: '🚡', name: 'aerial tramway', category: 'travel', keywords: ['tramway'] },
  { char: '🚀', name: 'rocket', category: 'travel', keywords: ['rocket', 'space'] },
  { char: '🛸', name: 'flying saucer', category: 'travel', keywords: ['ufo', 'space'] },
  { char: '🪐', name: 'ringed planet', category: 'travel', keywords: ['planet', 'space'] },
  { char: '🌠', name: 'shooting star', category: 'travel', keywords: ['star', 'wish'] },
  { char: '🌑', name: 'new moon', category: 'travel', keywords: ['moon'] },
  { char: '🌓', name: 'first quarter moon', category: 'travel', keywords: ['moon'] },
  { char: '🌕', name: 'full moon', category: 'travel', keywords: ['moon'] },
  { char: '🌙', name: 'crescent moon', category: 'travel', keywords: ['moon'] },
  { char: '🌞', name: 'sun with face', category: 'travel', keywords: ['sun', 'happy'] },
  { char: '⭐', name: 'star', category: 'travel', keywords: ['star'] },
  { char: '🌟', name: 'glowing star', category: 'travel', keywords: ['star'] },
  { char: '🌠', name: 'shooting star', category: 'travel', keywords: ['star'] },
  { char: '☁️', name: 'cloud', category: 'travel', keywords: ['cloud', 'weather'] },
  { char: '⛅', name: 'sun behind cloud', category: 'travel', keywords: ['cloud', 'sun'] },
  { char: '⛈️', name: 'cloud with lightning and rain', category: 'travel', keywords: ['storm', 'rain'] },
  { char: '🌤️', name: 'sun behind small cloud', category: 'travel', keywords: ['sun', 'cloud'] },
  { char: '🌥️', name: 'sun behind large cloud', category: 'travel', keywords: ['sun', 'cloud'] },
  { char: '🌦️', name: 'sun behind rain cloud', category: 'travel', keywords: ['sun', 'rain'] },
  { char: '🌧️', name: 'cloud with rain', category: 'travel', keywords: ['rain'] },
  { char: '🌨️', name: 'cloud with snow', category: 'travel', keywords: ['snow'] },
  { char: '🌩️', name: 'cloud with lightning', category: 'travel', keywords: ['lightning'] },
  { char: '🌪️', name: 'tornado', category: 'travel', keywords: ['tornado', 'weather'] },
  { char: '🌫️', name: 'fog', category: 'travel', keywords: ['fog'] },
  { char: '🌀', name: 'cyclone', category: 'travel', keywords: ['cyclone', 'weather'] },
  { char: '🌈', name: 'rainbow', category: 'travel', keywords: ['rainbow', 'colorful'] },
  { char: '⛱️', name: 'umbrella on ground', category: 'travel', keywords: ['beach', 'umbrella'] },
  { char: '☔', name: 'umbrella with rain drops', category: 'travel', keywords: ['rain', 'umbrella'] },
  { char: '⚡', name: 'high voltage', category: 'travel', keywords: ['lightning', 'power'] },
  { char: '❄️', name: 'snowflake', category: 'travel', keywords: ['snow', 'cold'] },
  { char: '🔥', name: 'fire', category: 'travel', keywords: ['fire', 'hot'] },
  { char: '💧', name: 'droplet', category: 'travel', keywords: ['water', 'drop'] },
  { char: '🌊', name: 'water wave', category: 'travel', keywords: ['ocean', 'wave'] },

  // Objects
  { char: '⌚', name: 'watch', category: 'objects', keywords: ['time', 'watch'] },
  { char: '📱', name: 'mobile phone', category: 'objects', keywords: ['phone', 'mobile'] },
  { char: '📲', name: 'mobile phone with arrow', category: 'objects', keywords: ['phone', 'call'] },
  { char: '💻', name: 'laptop', category: 'objects', keywords: ['computer', 'laptop', 'work'] },
  { char: '⌨️', name: 'keyboard', category: 'objects', keywords: ['computer', 'keyboard'] },
  { char: '🖱️', name: 'computer mouse', category: 'objects', keywords: ['computer', 'mouse'] },
  { char: '🖨️', name: 'printer', category: 'objects', keywords: ['printer', 'paper'] },
  { char: '🖲️', name: 'trackball', category: 'objects', keywords: ['computer', 'trackball'] },
  { char: '🕹️', name: 'joystick', category: 'objects', keywords: ['game', 'play'] },
  { char: '🗜️', name: 'clamp', category: 'objects', keywords: ['tool', 'clamp'] },
  { char: '💽', name: 'computer disk', category: 'objects', keywords: ['computer', 'disk'] },
  { char: '💾', name: 'floppy disk', category: 'objects', keywords: ['computer', 'save'] },
  { char: '💿', name: 'optical disk', category: 'objects', keywords: ['cd', 'dvd'] },
  { char: '📀', name: 'dvd', category: 'objects', keywords: ['cd', 'dvd'] },
  { char: '📼', name: 'videocassette', category: 'objects', keywords: ['vhs', 'video'] },
  { char: '📷', name: 'camera', category: 'objects', keywords: ['camera', 'photo'] },
  { char: '📸', name: 'camera with flash', category: 'objects', keywords: ['camera', 'photo'] },
  { char: '📹', name: 'video camera', category: 'objects', keywords: ['camera', 'video'] },
  { char: '🎥', name: 'movie camera', category: 'objects', keywords: ['camera', 'movie'] },
  { char: '📽️', name: 'film projector', category: 'objects', keywords: ['movie', 'projector'] },
  { char: '🎞️', name: 'film frames', category: 'objects', keywords: ['movie', 'film'] },
  { char: '📞', name: 'telephone receiver', category: 'objects', keywords: ['phone', 'call'] },
  { char: '☎️', name: 'telephone', category: 'objects', keywords: ['phone', 'call'] },
  { char: '📟', name: 'pager', category: 'objects', keywords: ['pager', 'beeper'] },
  { char: '📠', name: 'fax machine', category: 'objects', keywords: ['fax'] },
  { char: '📺', name: 'television', category: 'objects', keywords: ['tv', 'television'] },
  { char: '📻', name: 'radio', category: 'objects', keywords: ['radio'] },
  { char: '🎙️', name: 'studio microphone', category: 'objects', keywords: ['mic', 'radio'] },
  { char: '🎚️', name: 'level slider', category: 'objects', keywords: ['music', 'audio'] },
  { char: '🎛️', name: 'control knobs', category: 'objects', keywords: ['music', 'audio'] },
  { char: '🧭', name: 'compass', category: 'objects', keywords: ['compass', 'direction'] },
  { char: '⏱️', name: 'stopwatch', category: 'objects', keywords: ['time', 'stopwatch'] },
  { char: '⏲️', name: 'timer clock', category: 'objects', keywords: ['time', 'timer'] },
  { char: '⏰', name: 'alarm clock', category: 'objects', keywords: ['time', 'alarm'] },
  { char: '🕰️', name: 'mantelpiece clock', category: 'objects', keywords: ['time', 'clock'] },
  { char: '⏳', name: 'hourglass done', category: 'objects', keywords: ['time', 'hourglass'] },
  { char: '⌛', name: 'hourglass not done', category: 'objects', keywords: ['time', 'hourglass'] },
  { char: '📡', name: 'satellite antenna', category: 'objects', keywords: ['satellite', 'antenna'] },
  { char: '🔋', name: 'battery', category: 'objects', keywords: ['battery', 'power'] },
  { char: '🔌', name: 'electric plug', category: 'objects', keywords: ['electric', 'plug'] },
  { char: '💡', name: 'light bulb', category: 'objects', keywords: ['light', 'idea'] },
  { char: '🔦', name: 'flashlight', category: 'objects', keywords: ['light', 'torch'] },
  { char: '🕯️', name: 'candle', category: 'objects', keywords: ['light', 'candle'] },
  { char: '🪔', name: 'diya lamp', category: 'objects', keywords: ['light', 'diya'] },
  { char: '🧯', name: 'fire extinguisher', category: 'objects', keywords: ['fire', 'extinguisher'] },
  { char: '🛢️', name: 'oil drum', category: 'objects', keywords: ['oil', 'drum'] },
  { char: '💸', name: 'money with wings', category: 'objects', keywords: ['money', 'wings'] },
  { char: '💵', name: 'dollar banknote', category: 'objects', keywords: ['money', 'dollar'] },
  { char: '💴', name: 'yen banknote', category: 'objects', keywords: ['money', 'yen'] },
  { char: '💶', name: 'euro banknote', category: 'objects', keywords: ['money', 'euro'] },
  { char: '💷', name: 'pound banknote', category: 'objects', keywords: ['money', 'pound'] },
  { char: '💰', name: 'money bag', category: 'objects', keywords: ['money', 'rich'] },
  { char: '💳', name: 'credit card', category: 'objects', keywords: ['money', 'card'] },
  { char: '💎', name: 'gem stone', category: 'objects', keywords: ['diamond', 'gem'] },
  { char: '⚖️', name: 'balance scale', category: 'objects', keywords: ['balance', 'justice'] },
  { char: '🧰', name: 'toolbox', category: 'objects', keywords: ['tool', 'box'] },
  { char: '🔧', name: 'wrench', category: 'objects', keywords: ['tool', 'wrench'] },
  { char: '🔨', name: 'hammer', category: 'objects', keywords: ['tool', 'hammer'] },
  { char: '⚒️', name: 'hammer and pick', category: 'objects', keywords: ['tool', 'hammer'] },
  { char: '🛠️', name: 'hammer and wrench', category: 'objects', keywords: ['tool', 'hammer'] },
  { char: '⛏️', name: 'pick', category: 'objects', keywords: ['tool', 'pick'] },
  { char: '🔩', name: 'nut and bolt', category: 'objects', keywords: ['tool', 'bolt'] },
  { char: '⚙️', name: 'gear', category: 'objects', keywords: ['tool', 'gear'] },
  { char: '🧱', name: 'brick', category: 'objects', keywords: ['building', 'brick'] },
  { char: '⛓️', name: 'chains', category: 'objects', keywords: ['chain'] },
  { char: '🧲', name: 'magnet', category: 'objects', keywords: ['magnet'] },
  { char: '🔫', name: 'pistol', category: 'objects', keywords: ['gun', 'weapon'] },
  { char: '💣', name: 'bomb', category: 'objects', keywords: ['bomb', 'explode'] },
  { char: '🧨', name: 'firecracker', category: 'objects', keywords: ['firecracker', 'explode'] },
  { char: '🔪', name: 'kitchen knife', category: 'objects', keywords: ['knife', 'weapon'] },
  { char: '🗡️', name: 'dagger', category: 'objects', keywords: ['dagger', 'weapon'] },
  { char: '⚔️', name: 'crossed swords', category: 'objects', keywords: ['sword', 'weapon'] },
  { char: '🛡️', name: 'shield', category: 'objects', keywords: ['shield', 'weapon'] },
  { char: '🚬', name: 'cigarette', category: 'objects', keywords: ['smoke', 'cigarette'] },
  { char: '⚰️', name: 'coffin', category: 'objects', keywords: ['coffin', 'dead'] },
  { char: '⚱️', name: 'funeral urn', category: 'objects', keywords: ['urn', 'dead'] },
  { char: '🏺', name: 'amphora', category: 'objects', keywords: ['vase', 'jar'] },
  { char: '🔮', name: 'crystal ball', category: 'objects', keywords: ['magic', 'crystal'] },
  { char: '📿', name: 'prayer beads', category: 'objects', keywords: ['beads', 'religion'] },
  { char: '🧿', name: 'nazar amulet', category: 'objects', keywords: ['amulet', 'eye'] },
  { char: '💈', name: 'barber pole', category: 'objects', keywords: ['barber', 'hair'] },
  { char: '⚗️', name: 'alembic', category: 'objects', keywords: ['science', 'lab'] },
  { char: '🔭', name: 'telescope', category: 'objects', keywords: ['science', 'stars'] },
  { char: '🔬', name: 'microscope', category: 'objects', keywords: ['science', 'lab'] },
  { char: '🕳️', name: 'hole', category: 'objects', keywords: ['hole'] },
  { char: '🩹', name: 'adhesive bandage', category: 'objects', keywords: ['medical', 'bandage'] },
  { char: '🩺', name: 'stethoscope', category: 'objects', keywords: ['medical', 'doctor'] },
  { char: '💊', name: 'pill', category: 'objects', keywords: ['medical', 'medicine'] },
  { char: '💉', name: 'syringe', category: 'objects', keywords: ['medical', 'syringe'] },
  { char: '🩸', name: 'drop of blood', category: 'objects', keywords: ['medical', 'blood'] },
  { char: '🧬', name: 'dna', category: 'objects', keywords: ['science', 'dna'] },
  { char: '🌡️', name: 'thermometer', category: 'objects', keywords: ['medical', 'fever'] },
  { char: '🏷️', name: 'label', category: 'objects', keywords: ['label', 'tag'] },
  { char: '🔖', name: 'bookmark', category: 'objects', keywords: ['bookmark'] },
  { char: '🚽', name: 'toilet', category: 'objects', keywords: ['toilet', 'bathroom'] },
  { char: '🚿', name: 'shower', category: 'objects', keywords: ['shower', 'bathroom'] },
  { char: '🛁', name: 'bathtub', category: 'objects', keywords: ['bathtub', 'bathroom'] },
  { char: '🪒', name: 'razor', category: 'objects', keywords: ['razor', 'shave'] },
  { char: '🧴', name: 'lotion bottle', category: 'objects', keywords: ['lotion', 'bottle'] },
  { char: '🧷', name: 'safety pin', category: 'objects', keywords: ['pin', 'safety'] },
  { char: '🧹', name: 'broom', category: 'objects', keywords: ['broom', 'clean'] },
  { char: '🧺', name: 'basket', category: 'objects', keywords: ['basket'] },
  { char: '🧻', name: 'roll of paper', category: 'objects', keywords: ['paper', 'toilet'] },
  { char: '🧼', name: 'soap', category: 'objects', keywords: ['soap', 'clean'] },
  { char: '🧽', name: 'sponge', category: 'objects', keywords: ['sponge', 'clean'] },
  { char: '🧯', name: 'fire extinguisher', category: 'objects', keywords: ['fire', 'extinguisher'] },
  { char: '🛒', name: 'shopping cart', category: 'objects', keywords: ['shop', 'cart'] },

  // Flags
  { char: '🏁', name: 'chequered flag', category: 'flags', keywords: ['race', 'finish'] },
  { char: '🚩', name: 'triangular flag', category: 'flags', keywords: ['flag', 'warning'] },
  { char: '🎌', name: 'crossed flags', category: 'flags', keywords: ['flags', 'japan'] },
  { char: '🏴', name: 'black flag', category: 'flags', keywords: ['flag', 'black'] },
  { char: '🏳️', name: 'white flag', category: 'flags', keywords: ['flag', 'white'] },
  { char: '🏳️‍🌈', name: 'rainbow flag', category: 'flags', keywords: ['flag', 'pride'] },
  { char: '🏳️‍⚧️', name: 'transgender flag', category: 'flags', keywords: ['flag', 'trans'] },
  { char: '🏴‍☠️', name: 'pirate flag', category: 'flags', keywords: ['flag', 'pirate'] },
  { char: '🇦🇫', name: 'Afghanistan', category: 'flags', keywords: ['flag', 'afghanistan'] },
  { char: '🇦🇱', name: 'Albania', category: 'flags', keywords: ['flag', 'albania'] },
  { char: '🇩🇿', name: 'Algeria', category: 'flags', keywords: ['flag', 'algeria'] },
  { char: '🇦🇸', name: 'American Samoa', category: 'flags', keywords: ['flag', 'samoa'] },
  { char: '🇦🇩', name: 'Andorra', category: 'flags', keywords: ['flag', 'andorra'] },
  { char: '🇦🇴', name: 'Angola', category: 'flags', keywords: ['flag', 'angola'] },
  { char: '🇦🇮', name: 'Anguilla', category: 'flags', keywords: ['flag', 'anguilla'] },
  { char: '🇦🇶', name: 'Antarctica', category: 'flags', keywords: ['flag', 'antarctica'] },
  { char: '🇦🇬', name: 'Antigua & Barbuda', category: 'flags', keywords: ['flag', 'antigua'] },
  { char: '🇦🇷', name: 'Argentina', category: 'flags', keywords: ['flag', 'argentina'] },
  { char: '🇦🇲', name: 'Armenia', category: 'flags', keywords: ['flag', 'armenia'] },
  { char: '🇦🇼', name: 'Aruba', category: 'flags', keywords: ['flag', 'aruba'] },
  { char: '🇦🇺', name: 'Australia', category: 'flags', keywords: ['flag', 'australia'] },
  { char: '🇦🇹', name: 'Austria', category: 'flags', keywords: ['flag', 'austria'] },
  { char: '🇦🇿', name: 'Azerbaijan', category: 'flags', keywords: ['flag', 'azerbaijan'] },
  { char: '🇧🇸', name: 'Bahamas', category: 'flags', keywords: ['flag', 'bahamas'] },
  { char: '🇧🇭', name: 'Bahrain', category: 'flags', keywords: ['flag', 'bahrain'] },
  { char: '🇧🇩', name: 'Bangladesh', category: 'flags', keywords: ['flag', 'bangladesh'] },
  { char: '🇧🇧', name: 'Barbados', category: 'flags', keywords: ['flag', 'barbados'] },
  { char: '🇧🇾', name: 'Belarus', category: 'flags', keywords: ['flag', 'belarus'] },
  { char: '🇧🇪', name: 'Belgium', category: 'flags', keywords: ['flag', 'belgium'] },
  { char: '🇧🇿', name: 'Belize', category: 'flags', keywords: ['flag', 'belize'] },
  { char: '🇧🇯', name: 'Benin', category: 'flags', keywords: ['flag', 'benin'] },
  { char: '🇧🇲', name: 'Bermuda', category: 'flags', keywords: ['flag', 'bermuda'] },
  { char: '🇧🇹', name: 'Bhutan', category: 'flags', keywords: ['flag', 'bhutan'] },
  { char: '🇧🇴', name: 'Bolivia', category: 'flags', keywords: ['flag', 'bolivia'] },
  { char: '🇧🇦', name: 'Bosnia & Herzegovina', category: 'flags', keywords: ['flag', 'bosnia'] },
  { char: '🇧🇼', name: 'Botswana', category: 'flags', keywords: ['flag', 'botswana'] },
  { char: '🇧🇷', name: 'Brazil', category: 'flags', keywords: ['flag', 'brazil'] },
  { char: '🇻🇬', name: 'British Virgin Islands', category: 'flags', keywords: ['flag', 'virgin islands'] },
  { char: '🇧🇳', name: 'Brunei', category: 'flags', keywords: ['flag', 'brunei'] },
  { char: '🇧🇬', name: 'Bulgaria', category: 'flags', keywords: ['flag', 'bulgaria'] },
  { char: '🇧🇫', name: 'Burkina Faso', category: 'flags', keywords: ['flag', 'burkina'] },
  { char: '🇧🇮', name: 'Burundi', category: 'flags', keywords: ['flag', 'burundi'] },
  { char: '🇰🇭', name: 'Cambodia', category: 'flags', keywords: ['flag', 'cambodia'] },
  { char: '🇨🇲', name: 'Cameroon', category: 'flags', keywords: ['flag', 'cameroon'] },
  { char: '🇨🇦', name: 'Canada', category: 'flags', keywords: ['flag', 'canada'] },
  { char: '🇮🇨', name: 'Canary Islands', category: 'flags', keywords: ['flag', 'canary'] },
  { char: '🇨🇻', name: 'Cape Verde', category: 'flags', keywords: ['flag', 'cape verde'] },
  { char: '🇧🇶', name: 'Caribbean Netherlands', category: 'flags', keywords: ['flag', 'netherlands'] },
  { char: '🇰🇾', name: 'Cayman Islands', category: 'flags', keywords: ['flag', 'cayman'] },
  { char: '🇨🇫', name: 'Central African Republic', category: 'flags', keywords: ['flag', 'central african republic'] },
  { char: '🇹🇩', name: 'Chad', category: 'flags', keywords: ['flag', 'chad'] },
  { char: '🇨🇱', name: 'Chile', category: 'flags', keywords: ['flag', 'chile'] },
  { char: '🇨🇳', name: 'China', category: 'flags', keywords: ['flag', 'china'] },
  { char: '🇨🇽', name: 'Christmas Island', category: 'flags', keywords: ['flag', 'christmas'] },
  { char: '🇨🇨', name: 'Cocos (Keeling) Islands', category: 'flags', keywords: ['flag', 'cocos'] },
  { char: '🇨🇴', name: 'Colombia', category: 'flags', keywords: ['flag', 'colombia'] },
  { char: '🇰🇲', name: 'Comoros', category: 'flags', keywords: ['flag', 'comoros'] },
  { char: '🇨🇬', name: 'Congo - Brazzaville', category: 'flags', keywords: ['flag', 'congo'] },
  { char: '🇨🇩', name: 'Congo - Kinshasa', category: 'flags', keywords: ['flag', 'congo'] },
  { char: '🇨🇰', name: 'Cook Islands', category: 'flags', keywords: ['flag', 'cook islands'] },
  { char: '🇨🇷', name: 'Costa Rica', category: 'flags', keywords: ['flag', 'costa rica'] },
  { char: '🇨🇮', name: 'Côte d’Ivoire', category: 'flags', keywords: ['flag', 'ivory coast'] },
  { char: '🇭🇷', name: 'Croatia', category: 'flags', keywords: ['flag', 'croatia'] },
  { char: '🇨🇺', name: 'Cuba', category: 'flags', keywords: ['flag', 'cuba'] },
  { char: '🇨🇼', name: 'Curaçao', category: 'flags', keywords: ['flag', 'curacao'] },
  { char: '🇨🇾', name: 'Cyprus', category: 'flags', keywords: ['flag', 'cyprus'] },
  { char: '🇨🇿', name: 'Czechia', category: 'flags', keywords: ['flag', 'czech republic'] },
  { char: '🇩🇰', name: 'Denmark', category: 'flags', keywords: ['flag', 'denmark'] },
  { char: '🇩🇯', name: 'Djibouti', category: 'flags', keywords: ['flag', 'djibouti'] },
  { char: '🇩🇲', name: 'Dominica', category: 'flags', keywords: ['flag', 'dominica'] },
  { char: '🇩🇴', name: 'Dominican Republic', category: 'flags', keywords: ['flag', 'dominican republic'] },
  { char: '🇪🇨', name: 'Ecuador', category: 'flags', keywords: ['flag', 'ecuador'] },
  { char: '🇪🇬', name: 'Egypt', category: 'flags', keywords: ['flag', 'egypt'] },
  { char: '🇸🇻', name: 'El Salvador', category: 'flags', keywords: ['flag', 'el salvador'] },
  { char: '🇬🇶', name: 'Equatorial Guinea', category: 'flags', keywords: ['flag', 'equatorial guinea'] },
  { char: '🇪🇷', name: 'Eritrea', category: 'flags', keywords: ['flag', 'eritrea'] },
  { char: '🇪🇪', name: 'Estonia', category: 'flags', keywords: ['flag', 'estonia'] },
  { char: '🇸🇿', name: 'Eswatini', category: 'flags', keywords: ['flag', 'eswatini'] },
  { char: '🇪🇹', name: 'Ethiopia', category: 'flags', keywords: ['flag', 'ethiopia'] },
  { char: '🇪🇺', name: 'European Union', category: 'flags', keywords: ['flag', 'eu'] },
  { char: '🇫🇰', name: 'Falkland Islands', category: 'flags', keywords: ['flag', 'falkland'] },
  { char: '🇫🇴', name: 'Faroe Islands', category: 'flags', keywords: ['flag', 'faroe'] },
  { char: '🇫🇯', name: 'Fiji', category: 'flags', keywords: ['flag', 'fiji'] },
  { char: '🇫🇮', name: 'Finland', category: 'flags', keywords: ['flag', 'finland'] },
  { char: '🇫🇷', name: 'France', category: 'flags', keywords: ['flag', 'france'] },
  { char: '🇬🇫', name: 'French Guiana', category: 'flags', keywords: ['flag', 'french guiana'] },
  { char: '🇵🇫', name: 'French Polynesia', category: 'flags', keywords: ['flag', 'french polynesia'] },
  { char: '🇹🇫', name: 'French Southern Territories', category: 'flags', keywords: ['flag', 'french southern territories'] },
  { char: '🇬🇦', name: 'Gabon', category: 'flags', keywords: ['flag', 'gabon'] },
  { char: '🇬🇲', name: 'Gambia', category: 'flags', keywords: ['flag', 'gambia'] },
  { char: '🇬🇪', name: 'Georgia', category: 'flags', keywords: ['flag', 'georgia'] },
  { char: '🇩🇪', name: 'Germany', category: 'flags', keywords: ['flag', 'germany'] },
  { char: '🇬🇭', name: 'Ghana', category: 'flags', keywords: ['flag', 'ghana'] },
  { char: '🇬🇮', name: 'Gibraltar', category: 'flags', keywords: ['flag', 'gibraltar'] },
  { char: '🇬🇷', name: 'Greece', category: 'flags', keywords: ['flag', 'greece'] },
  { char: '🇬🇱', name: 'Greenland', category: 'flags', keywords: ['flag', 'greenland'] },
  { char: '🇬🇩', name: 'Grenada', category: 'flags', keywords: ['flag', 'grenada'] },
  { char: '🇬🇵', name: 'Guadeloupe', category: 'flags', keywords: ['flag', 'guadeloupe'] },
  { char: '🇬🇺', name: 'Guam', category: 'flags', keywords: ['flag', 'guam'] },
  { char: '🇬🇹', name: 'Guatemala', category: 'flags', keywords: ['flag', 'guatemala'] },
  { char: '🇬🇬', name: 'Guernsey', category: 'flags', keywords: ['flag', 'guernsey'] },
  { char: '🇬🇳', name: 'Guinea', category: 'flags', keywords: ['flag', 'guinea'] },
  { char: '🇬🇼', name: 'Guinea-Bissau', category: 'flags', keywords: ['flag', 'guinea-bissau'] },
  { char: '🇬🇾', name: 'Guyana', category: 'flags', keywords: ['flag', 'guyana'] },
  { char: '🇭🇹', name: 'Haiti', category: 'flags', keywords: ['flag', 'haiti'] },
  { char: '🇭🇳', name: 'Honduras', category: 'flags', keywords: ['flag', 'honduras'] },
  { char: '🇭🇰', name: 'Hong Kong SAR China', category: 'flags', keywords: ['flag', 'hong kong'] },
  { char: '🇭🇺', name: 'Hungary', category: 'flags', keywords: ['flag', 'hungary'] },
  { char: '🇮🇸', name: 'Iceland', category: 'flags', keywords: ['flag', 'iceland'] },
  { char: '🇮🇳', name: 'India', category: 'flags', keywords: ['flag', 'india'] },
  { char: '🇮🇩', name: 'Indonesia', category: 'flags', keywords: ['flag', 'indonesia'] },
  { char: '🇮🇷', name: 'Iran', category: 'flags', keywords: ['flag', 'iran'] },
  { char: '🇮🇶', name: 'Iraq', category: 'flags', keywords: ['flag', 'iraq'] },
  { char: '🇮🇪', name: 'Ireland', category: 'flags', keywords: ['flag', 'ireland'] },
  { char: '🇮🇲', name: 'Isle of Man', category: 'flags', keywords: ['flag', 'isle of man'] },
  { char: '🇮🇱', name: 'Israel', category: 'flags', keywords: ['flag', 'israel'] },
  { char: '🇮🇹', name: 'Italy', category: 'flags', keywords: ['flag', 'italy'] },
  { char: '🇯🇲', name: 'Jamaica', category: 'flags', keywords: ['flag', 'jamaica'] },
  { char: '🇯🇵', name: 'Japan', category: 'flags', keywords: ['flag', 'japan'] },
  { char: '🇯🇪', name: 'Jersey', category: 'flags', keywords: ['flag', 'jersey'] },
  { char: '🇯🇴', name: 'Jordan', category: 'flags', keywords: ['flag', 'jordan'] },
  { char: '🇰🇿', name: 'Kazakhstan', category: 'flags', keywords: ['flag', 'kazakhstan'] },
  { char: '🇰🇪', name: 'Kenya', category: 'flags', keywords: ['flag', 'kenya'] },
  { char: '🇰🇮', name: 'Kiribati', category: 'flags', keywords: ['flag', 'kiribati'] },
  { char: '🇽🇰', name: 'Kosovo', category: 'flags', keywords: ['flag', 'kosovo'] },
  { char: '🇰🇼', name: 'Kuwait', category: 'flags', keywords: ['flag', 'kuwait'] },
  { char: '🇰🇬', name: 'Kyrgyzstan', category: 'flags', keywords: ['flag', 'kyrgyzstan'] },
  { char: '🇱🇦', name: 'Laos', category: 'flags', keywords: ['flag', 'laos'] },
  { char: '🇱🇻', name: 'Latvia', category: 'flags', keywords: ['flag', 'latvia'] },
  { char: '🇱🇧', name: 'Lebanon', category: 'flags', keywords: ['flag', 'lebanon'] },
  { char: '🇱🇸', name: 'Lesotho', category: 'flags', keywords: ['flag', 'lesotho'] },
  { char: '🇱🇷', name: 'Liberia', category: 'flags', keywords: ['flag', 'liberia'] },
  { char: '🇱🇾', name: 'Libya', category: 'flags', keywords: ['flag', 'libya'] },
  { char: '🇱🇮', name: 'Liechtenstein', category: 'flags', keywords: ['flag', 'liechtenstein'] },
  { char: '🇱🇹', name: 'Lithuania', category: 'flags', keywords: ['flag', 'lithuania'] },
  { char: '🇱🇺', name: 'Luxembourg', category: 'flags', keywords: ['flag', 'luxembourg'] },
  { char: '🇲🇴', name: 'Macao SAR China', category: 'flags', keywords: ['flag', 'macao'] },
  { char: '🇲🇬', name: 'Madagascar', category: 'flags', keywords: ['flag', 'madagascar'] },
  { char: '🇲🇼', name: 'Malawi', category: 'flags', keywords: ['flag', 'malawi'] },
  { char: '🇲🇾', name: 'Malaysia', category: 'flags', keywords: ['flag', 'malaysia'] },
  { char: '🇲🇻', name: 'Maldives', category: 'flags', keywords: ['flag', 'maldives'] },
  { char: '🇲🇱', name: 'Mali', category: 'flags', keywords: ['flag', 'mali'] },
  { char: '🇲🇹', name: 'Malta', category: 'flags', keywords: ['flag', 'malta'] },
  { char: '🇲🇭', name: 'Marshall Islands', category: 'flags', keywords: ['flag', 'marshall islands'] },
  { char: '🇲🇶', name: 'Martinique', category: 'flags', keywords: ['flag', 'martinique'] },
  { char: '🇲🇷', name: 'Mauritania', category: 'flags', keywords: ['flag', 'mauritania'] },
  { char: '🇲🇺', name: 'Mauritius', category: 'flags', keywords: ['flag', 'mauritius'] },
  { char: '🇾🇹', name: 'Mayotte', category: 'flags', keywords: ['flag', 'mayotte'] },
  { char: '🇲🇽', name: 'Mexico', category: 'flags', keywords: ['flag', 'mexico'] },
  { char: '🇫🇲', name: 'Micronesia', category: 'flags', keywords: ['flag', 'micronesia'] },
  { char: '🇲🇩', name: 'Moldova', category: 'flags', keywords: ['flag', 'moldova'] },
  { char: '🇲🇨', name: 'Monaco', category: 'flags', keywords: ['flag', 'monaco'] },
  { char: '🇲🇳', name: 'Mongolia', category: 'flags', keywords: ['flag', 'mongolia'] },
  { char: '🇲🇪', name: 'Montenegro', category: 'flags', keywords: ['flag', 'montenegro'] },
  { char: '🇲🇸', name: 'Montserrat', category: 'flags', keywords: ['flag', 'montserrat'] },
  { char: '🇲🇦', name: 'Morocco', category: 'flags', keywords: ['flag', 'morocco'] },
  { char: '🇲🇿', name: 'Mozambique', category: 'flags', keywords: ['flag', 'mozambique'] },
  { char: '🇲🇲', name: 'Myanmar (Burma)', category: 'flags', keywords: ['flag', 'myanmar'] },
  { char: '🇳🇦', name: 'Namibia', category: 'flags', keywords: ['flag', 'namibia'] },
  { char: '🇳🇷', name: 'Nauru', category: 'flags', keywords: ['flag', 'nauru'] },
  { char: '🇳🇵', name: 'Nepal', category: 'flags', keywords: ['flag', 'nepal'] },
  { char: '🇳🇱', name: 'Netherlands', category: 'flags', keywords: ['flag', 'netherlands'] },
  { char: '🇳🇨', name: 'New Caledonia', category: 'flags', keywords: ['flag', 'new caledonia'] },
  { char: '🇳🇿', name: 'New Zealand', category: 'flags', keywords: ['flag', 'new zealand'] },
  { char: '🇳🇮', name: 'Nicaragua', category: 'flags', keywords: ['flag', 'nicaragua'] },
  { char: '🇳🇪', name: 'Niger', category: 'flags', keywords: ['flag', 'niger'] },
  { char: '🇳🇬', name: 'Nigeria', category: 'flags', keywords: ['flag', 'nigeria'] },
  { char: '🇳🇺', name: 'Niue', category: 'flags', keywords: ['flag', 'niue'] },
  { char: '🇳🇫', name: 'Norfolk Island', category: 'flags', keywords: ['flag', 'norfolk island'] },
  { char: '🇰🇵', name: 'North Korea', category: 'flags', keywords: ['flag', 'north korea'] },
  { char: '🇲🇰', name: 'North Macedonia', category: 'flags', keywords: ['flag', 'macedonia'] },
  { char: '🇲🇵', name: 'Northern Mariana Islands', category: 'flags', keywords: ['flag', 'mariana islands'] },
  { char: '🇳🇴', name: 'Norway', category: 'flags', keywords: ['flag', 'norway'] },
  { char: '🇴🇲', name: 'Oman', category: 'flags', keywords: ['flag', 'oman'] },
  { char: '🇵🇰', name: 'Pakistan', category: 'flags', keywords: ['flag', 'pakistan'] },
  { char: '🇵🇼', name: 'Palau', category: 'flags', keywords: ['flag', 'palau'] },
  { char: '🇵🇸', name: 'Palestinian Territories', category: 'flags', keywords: ['flag', 'palestine'] },
  { char: '🇵🇦', name: 'Panama', category: 'flags', keywords: ['flag', 'panama'] },
  { char: '🇵🇬', name: 'Papua New Guinea', category: 'flags', keywords: ['flag', 'papua new guinea'] },
  { char: '🇵🇾', name: 'Paraguay', category: 'flags', keywords: ['flag', 'paraguay'] },
  { char: '🇵🇪', name: 'Peru', category: 'flags', keywords: ['flag', 'peru'] },
  { char: '🇵🇭', name: 'Philippines', category: 'flags', keywords: ['flag', 'philippines'] },
  { char: '🇵🇳', name: 'Pitcairn Islands', category: 'flags', keywords: ['flag', 'pitcairn islands'] },
  { char: '🇵🇱', name: 'Poland', category: 'flags', keywords: ['flag', 'poland'] },
  { char: '🇵🇹', name: 'Portugal', category: 'flags', keywords: ['flag', 'portugal'] },
  { char: '🇵🇷', name: 'Puerto Rico', category: 'flags', keywords: ['flag', 'puerto rico'] },
  { char: '🇶🇦', name: 'Qatar', category: 'flags', keywords: ['flag', 'qatar'] },
  { char: '🇷🇪', name: 'Réunion', category: 'flags', keywords: ['flag', 'reunion'] },
  { char: '🇷🇴', name: 'Romania', category: 'flags', keywords: ['flag', 'romania'] },
  { char: '🇷🇺', name: 'Russia', category: 'flags', keywords: ['flag', 'russia'] },
  { char: '🇷🇼', name: 'Rwanda', category: 'flags', keywords: ['flag', 'rwanda'] },
  { char: '🇼🇸', name: 'Samoa', category: 'flags', keywords: ['flag', 'samoa'] },
  { char: '🇸🇲', name: 'San Marino', category: 'flags', keywords: ['flag', 'san marino'] },
  { char: '🇸🇹', name: 'São Tomé & Príncipe', category: 'flags', keywords: ['flag', 'sao tome'] },
  { char: '🇸🇦', name: 'Saudi Arabia', category: 'flags', keywords: ['flag', 'saudi arabia'] },
  { char: '🇸🇳', name: 'Senegal', category: 'flags', keywords: ['flag', 'senegal'] },
  { char: '🇷🇸', name: 'Serbia', category: 'flags', keywords: ['flag', 'serbia'] },
  { char: '🇸🇨', name: 'Seychelles', category: 'flags', keywords: ['flag', 'seychelles'] },
  { char: '🇸🇱', name: 'Sierra Leone', category: 'flags', keywords: ['flag', 'sierra leone'] },
  { char: '🇸🇬', name: 'Singapore', category: 'flags', keywords: ['flag', 'singapore'] },
  { char: '🇸🇽', name: 'Sint Maarten', category: 'flags', keywords: ['flag', 'sint maarten'] },
  { char: '🇸🇰', name: 'Slovakia', category: 'flags', keywords: ['flag', 'slovakia'] },
  { char: '🇸🇮', name: 'Slovenia', category: 'flags', keywords: ['flag', 'slovenia'] },
  { char: '🇸🇧', name: 'Solomon Islands', category: 'flags', keywords: ['flag', 'solomon islands'] },
  { char: '🇸🇴', name: 'Somalia', category: 'flags', keywords: ['flag', 'somalia'] },
  { char: '🇿🇦', name: 'South Africa', category: 'flags', keywords: ['flag', 'south africa'] },
  { char: '🇬🇸', name: 'South Georgia & South Sandwich Islands', category: 'flags', keywords: ['flag', 'south georgia'] },
  { char: '🇰🇷', name: 'South Korea', category: 'flags', keywords: ['flag', 'south korea'] },
  { char: '🇸🇸', name: 'South Sudan', category: 'flags', keywords: ['flag', 'south sudan'] },
  { char: '🇪🇸', name: 'Spain', category: 'flags', keywords: ['flag', 'spain'] },
  { char: '🇱🇰', name: 'Sri Lanka', category: 'flags', keywords: ['flag', 'sri lanka'] },
  { char: '🇧🇱', name: 'St. Barthélemy', category: 'flags', keywords: ['flag', 'st barthelemy'] },
  { char: '🇸🇭', name: 'St. Helena', category: 'flags', keywords: ['flag', 'st helena'] },
  { char: '🇰🇳', name: 'St. Kitts & Nevis', category: 'flags', keywords: ['flag', 'st kitts'] },
  { char: '🇱🇨', name: 'St. Lucia', category: 'flags', keywords: ['flag', 'st lucia'] },
  { char: '🇲🇫', name: 'St. Martin', category: 'flags', keywords: ['flag', 'st martin'] },
  { char: '🇵🇲', name: 'St. Pierre & Miquelon', category: 'flags', keywords: ['flag', 'st pierre'] },
  { char: '🇻🇨', name: 'St. Vincent & Grenadines', category: 'flags', keywords: ['flag', 'st vincent'] },
  { char: '🇸🇩', name: 'Sudan', category: 'flags', keywords: ['flag', 'sudan'] },
  { char: '🇸🇷', name: 'Suriname', category: 'flags', keywords: ['flag', 'suriname'] },
  { char: '🇸🇯', name: 'Svalbard & Jan Mayen', category: 'flags', keywords: ['flag', 'svalbard'] },
  { char: '🇸🇪', name: 'Sweden', category: 'flags', keywords: ['flag', 'sweden'] },
  { char: '🇨🇭', name: 'Switzerland', category: 'flags', keywords: ['flag', 'switzerland'] },
  { char: '🇸🇾', name: 'Syria', category: 'flags', keywords: ['flag', 'syria'] },
  { char: '🇹🇼', name: 'Taiwan', category: 'flags', keywords: ['flag', 'taiwan'] },
  { char: '🇹🇯', name: 'Tajikistan', category: 'flags', keywords: ['flag', 'tajikistan'] },
  { char: '🇹🇿', name: 'Tanzania', category: 'flags', keywords: ['flag', 'tanzania'] },
  { char: '🇹🇭', name: 'Thailand', category: 'flags', keywords: ['flag', 'thailand'] },
  { char: '🇹🇱', name: 'Timor-Leste', category: 'flags', keywords: ['flag', 'timor-leste'] },
  { char: '🇹🇬', name: 'Togo', category: 'flags', keywords: ['flag', 'togo'] },
  { char: '🇹🇰', name: 'Tokelau', category: 'flags', keywords: ['flag', 'tokelau'] },
  { char: '🇹🇴', name: 'Tonga', category: 'flags', keywords: ['flag', 'tonga'] },
  { char: '🇹🇹', name: 'Trinidad & Tobago', category: 'flags', keywords: ['flag', 'trinidad'] },
  { char: '🇹🇳', name: 'Tunisia', category: 'flags', keywords: ['flag', 'tunisia'] },
  { char: '🇹🇷', name: 'Turkey', category: 'flags', keywords: ['flag', 'turkey'] },
  { char: '🇹🇲', name: 'Turkmenistan', category: 'flags', keywords: ['flag', 'turkmenistan'] },
  { char: '🇹🇨', name: 'Turks & Caicos Islands', category: 'flags', keywords: ['flag', 'turks and caicos'] },
  { char: '🇹🇻', name: 'Tuvalu', category: 'flags', keywords: ['flag', 'tuvalu'] },
  { char: '🇺🇲', name: 'U.S. Outlying Islands', category: 'flags', keywords: ['flag', 'us'] },
  { char: '🇺🇬', name: 'Uganda', category: 'flags', keywords: ['flag', 'uganda'] },
  { char: '🇺🇦', name: 'Ukraine', category: 'flags', keywords: ['flag', 'ukraine'] },
  { char: '🇦🇪', name: 'United Arab Emirates', category: 'flags', keywords: ['flag', 'uae'] },
  { char: '🇬🇧', name: 'United Kingdom', category: 'flags', keywords: ['flag', 'uk'] },
  { char: '🇺🇳', name: 'United Nations', category: 'flags', keywords: ['flag', 'un'] },
  { char: '🇺🇸', name: 'United States', category: 'flags', keywords: ['flag', 'us'] },
  { char: '🇺🇾', name: 'Uruguay', category: 'flags', keywords: ['flag', 'uruguay'] },
  { char: '🇺🇿', name: 'Uzbekistan', category: 'flags', keywords: ['flag', 'uzbekistan'] },
  { char: '🇻🇺', name: 'Vanuatu', category: 'flags', keywords: ['flag', 'vanuatu'] },
  { char: '🇻🇦', name: 'Vatican City', category: 'flags', keywords: ['flag', 'vatican'] },
  { char: '🇻🇪', name: 'Venezuela', category: 'flags', keywords: ['flag', 'venezuela'] },
  { char: '🇻🇳', name: 'Vietnam', category: 'flags', keywords: ['flag', 'vietnam'] },
  { char: '🇻🇮', name: 'U.S. Virgin Islands', category: 'flags', keywords: ['flag', 'virgin islands'] },
  { char: '🇼🇫', name: 'Wallis & Futuna', category: 'flags', keywords: ['flag', 'wallis and futuna'] },
  { char: '🇪🇭', name: 'Western Sahara', category: 'flags', keywords: ['flag', 'western sahara'] },
  { char: '🇾🇪', name: 'Yemen', category: 'flags', keywords: ['flag', 'yemen'] },
  { char: '🇿🇲', name: 'Zambia', category: 'flags', keywords: ['flag', 'zambia'] },
  { char: '🇿🇼', name: 'Zimbabwe', category: 'flags', keywords: ['flag', 'zimbabwe'] },
  { char: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', name: 'England', category: 'flags', keywords: ['flag', 'england'] },
  { char: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', name: 'Scotland', category: 'flags', keywords: ['flag', 'scotland'] },
  { char: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', name: 'Wales', category: 'flags', keywords: ['flag', 'wales'] },
];


export const emojiCategories = {
  recent: { name: 'Recently Used', icon: '🕒' },
  smileys: { name: 'Smileys & People', icon: '😊' },
  animals: { name: 'Animals & Nature', icon: '🐶' },
  food: { name: 'Food & Drink', icon: '🍕' },
  activities: { name: 'Activities', icon: '⚽' },
  travel: { name: 'Travel & Places', icon: '✈️' },
  objects: { name: 'Objects', icon: '💡' },
  symbols: { name: 'Symbols', icon: '❤️' },
  flags: { name: 'Flags', icon: '🏁' },
};
